package com.skillSwap.Entity;

public enum NotificationType {
	CHAT_MESSAGE,
	SESSION_REQUESTED,
	SESSION_ACCEPTED,
	SESSION_REJECTED,
	SESSION_CANCELLED,
	SESSION_COMPLETED,
	SESSION_REMINDER,
	REVIEW_RECEIVED
}
